### ISSUE TITLE
Configure RSEs in Rucio

### ISSUE THREAD

**Issue by egazzarr** [vre-hub/vre#16]
CRIC can be used as a library for RSEs configuration details (ref. https://github.com/cern-vre/project/issues/15). With a script running in a cronjob, this information can then be pulled from CRIC and imported into rucio.

```[tasklist]
### Tasks
- [ ] Create RSEs in a new CRIC instance
- [x] Implement this script as a cronjob: https://github.com/ESCAPE-WP2/Utilities-and-Operations-Scripts/tree/master/cric-rucio-sync
- [ ] Configure REANA share as Rucio RSE #19
- [ ] https://github.com/vre-hub/vre/issues/76
```

**Comment by goseind** [comment]
@garciagenrique maybe for testing we deploy this: https://github.com/goseind/k8s-tutorial/blob/master/xrd.yaml

**Comment by garciagenrique** [comment]
Two RSEs added to the CRE-VRE cluster: `EULAKE-1` and `LAPP-DCACHE`.

Followed this documentation: https://github.com/cern-vre/cern-vre/wiki/Components#adding-rses-to-the-rucio-instance

**Comment by garciagenrique** [comment]
Uploads to `EULAKE-1` are working fine, we receive a warning that we don't know why it's appearing. RUCIO team contacted.

```
/root/envs-virtualenv/rucio-cli/lib/python3.6/site-packages/urllib3/connectionpool.py:1050: InsecureRequestWarning: Unverified HTTPS request is being made to host 'vre-rucio.cern.ch'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  InsecureRequestWarning,
```

**Comment by garciagenrique** [comment]
It seems that the above `Warning` was also appearing in the `escape-gitops` cluster.

**Comment by garciagenrique** [comment]
- @egazzarr  configured CNAF-STROM in the VRE. 

 - `CESNET-S3` gives the following problem after the DB was upgraded:
```bash
$ rucio-admin rse info CESNET-S3
Database exception.
Details: An unknown Database Exception has ocurred.
Rucio exited with an unexpected/unknown error, please provide the traceback below to the developers.
Traceback (most recent call last):
  File "/root/envs-virtualenv/rucio-cli/bin/rucio-admin", line 97, in new_funct
    return function(*args, **kwargs)
  File "/root/envs-virtualenv/rucio-cli/bin/rucio-admin", line 530, in info_rse
    rseinfo = client.get_rse(rse=args.rse)
  File "/root/envs-virtualenv/rucio-cli/lib/python3.6/site-packages/rucio/client/rseclient.py", line 50, in get_rse
    raise exc_cls(exc_msg)
rucio.common.exception.DatabaseException: Database exception.
Details: An unknown Database Exception has ocurred.
```
   - Erasing all replicas and files within the RSE:
```bash
$ rucio list-rules --account=<ACCOUNT_NAME>
$ rucio delete-rule <RULE_ID>
```
 - However, some files are still there
```bash
# Connect to the PSQL DB
rucio=> SELECT * FROM replicas WHERE rse_id = '<RSE_ID>';

# To get the rse-id: (f.ex:)
$ rucio list-rse-usage <RSE_NAME>
```

Issue being investigated

**Comment by goseind** [comment]
### Current status:
* Investigation of participation and functioning of current/old RSEs: https://docs.google.com/spreadsheets/d/1tp3osag7GrH_8TNd3R_LkfPOdAe71LwZd82L-UHM7WI/edit?usp=sharing
* Request of new endpoints for these RSEs to use with the new Rucio instance

**Comment by garciagenrique** [comment]
IMO, I will take out this [script](https://github.com/vre-hub/vre/blob/main/infrastructure/scripts/rucio-add-rse.sh) because it might lead to wrong RSE configuration. 
If everybody agrees we could just add a section on the Wiki explaining the main attributes and points to be configured, but without proposing a template.

**Comment by goseind** [comment]
CRIC will not be used atm. Ne RSE endpoints will be added as they come in.
