### ISSUE TITLE
Manage Rucio by flux II

### ISSUE THREAD

**Issue by garciagenrique** [vre-hub/vre#163]
Less critical tasks - related with Issue #138 

```[tasklist]
### Tasks
- [x] Solve https://github.com/vre-hub/vre/issues/138
- [ ] delete all the 'rucio' namespace which was applied with Terraform  - https://github.com/vre-hub/vre/issues/159
- [x] test cronjobs running Rucio actions and add them to flux
             - [ ] Revisit `escape-gitops` cronjobs and see which one are missing/still needed
- [ ] https://github.com/vre-hub/vre/issues/201
```
