### ISSUE TITLE
Install JupyterHub in the cern-vre cluster via tf helm provider

### ISSUE THREAD

**Issue by goseind** [vre-hub/vre#21]
### Information

* Versions of the helm chart: https://jupyterhub.github.io/helm-chart/
* Chart: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/blob/main/jupyterhub/Chart.yaml and configuration ref: https://z2jh.jupyter.org/en/stable/resources/reference.html#helm-chart-configuration-reference
* Docs: https://github.com/jupyterhub/helm-chart
* https://github.com/jupyterhub/repo2docker
* OAuth configuration and examples: https://z2jh.jupyter.org/en/stable/administrator/authentication.html#oauth2-based-authentication

### Questions

- (how) can sessions be stored for longer periods of time? e. g. https://pypi.org/project/dill/
- would a similar solution to Codespaces/Gitpod self-hosted (https://www.gitpod.io/docs/configure/self-hosted/latest) be a solution?
- compare to SWAN and Binderhub: https://jupyter.org/binder solutions

```[tasklist]
### Tasks
- [x] Install z2jh helm chart with basic configuration
- [x] Expose the service to the outside with SSL
- [x] Configure auth/login with IAM ESCAPE VO instance
- [x] Create a new database called `jhub` in `vre` dbod instance https://dbod.web.cern.ch/pages/dashboard
- [ ] https://github.com/cern-vre/cern-vre/issues/53
- [ ] https://github.com/cern-vre/cern-vre/issues/45
- [x] Open the Firewall for this service
- [x] Configure CVMFS as an `extraVolume`
- [x] Configure additional extra volumes
- [x] Transfer other relevant settings from the old VRE configuration (reducing complexity)
- [x] Solve problem/configure user persistent storage with PVCs
- [x] Think about other useful improvements and configuration settings for the chart
- [x] **Documentation on everything in the Wiki**
- [x] Investigate https://github.com/jupyterhub/binderhub installation
- [x] Investigate multiple sessions ref. https://github.com/jupyterlab/jupyterlab/pull/4041
- [ ] https://github.com/vre-hub/vre/issues/64
- [x] Move chart to flux
```

**Comment by goseind** [comment]
![IMG_20230130_172300.jpg](https://user-images.githubusercontent.com/87760323/215533982-34c695f9-39db-4a43-8834-8091f20296e0.jpg)

**Comment by garciagenrique** [comment]
- JupyterHub was installed following the [zero2jupyterhub documentation](https://z2jh.jupyter.org/en/stable/jupyterhub/installation.html#installing-jupyterhub) and using helm charts.
    - The `config.yaml` file is empty so that z2jh starts with the default values.
    - However, the deployment won't succeed because there is no storage assigned to the cluster. See below:

 -  Currently the HUB pod is starting (`Pending` mode) with the following error
```
|   Type     Reason            Age                  From               Message                                    │
│   ----     ------            ----                 ----               -------                                    │
│   Warning  FailedScheduling  19m (x309 over 26h)  default-scheduler  0/3 nodes are available: 3 pod has unbound │
│  immediate PersistentVolumeClaims. preemption: 0/3 nodes are available: 3 Preemption is not helpful for schedul │
│ ing.
```

This error is connected with the problem @goseind is stressing above: why `static` vs `dynamic` storage for the cluster.

**Comment by garciagenrique** [comment]
The following commands where used for the deployment (helm needs to be installed, of course)

```bash
$ helm repo add jupyterhub https://jupyterhub.github.io/helm-chart/
$ helm repo update
```

To install/updated, just modify the `config.yaml` file, save it and run
```bash
$ helm upgrade --cleanup-on-fail \
  --install z2jh jupyterhub/jupyterhub \
  --namespace jupyterhub \
  --create-namespace \
  --version=2.0.0 \
  --values config.yaml
```

The des installation of the helm chart does not work really well. The way it's currently done is by logging into `k9s`, selecting the `jupyterhub` (or whoever it was called), and erasing it completely.

**Comment by goseind** [comment]
I have requested a quota change for the number of shares, so we can use dynamically provisioned storage.

**Comment by goseind** [comment]
Done, quota updated to 200 shares.


![Image](https://user-images.githubusercontent.com/87760323/216958442-988aeb1c-fe28-4dc7-9008-af46932e7836.png)

**Comment by goseind** [comment]
JupyterHub is running under http://137.138.226.35 (IP subject to change). Current status:

- Update on Quota Question [here](https://cern.service-now.com/service-portal?id=ticket&table=incident&n=INC3374871)
- LBaaS automatic LB provisioning was having issues again (see [SNOW issue](https://cern.service-now.com/service-portal?id=ticket&table=incident&n=INC3375104)), thus creating the LB manually like so `openstack loadbalancer create --name kube_service_8d85602e-7816-4153-b85b-ea86586e47c1_jhub_proxy-public --vip-network-id public` and passing the IP into the helm values `loadBalancerIP`.
- `sqlite-memory` db type is just for testing and needs to be replaced by DBOD postgres db.
- Due to the usage of [`podSecurityContext`](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#podsecuritycontext-v1-core) also [here](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/), we need to set fsGroupChangePolicy: "OnRootMismatch" as per default the shares are owned by `root:root`, and writable only by root (ref. https://kubernetes.docs.cern.ch/docs/storage/fileshares/#running-pods-with-fsgroup-security-context). Setting the value through `extraPodConfig` as described [here](https://z2jh.jupyter.org/en/stable/resources/reference.html#singleuser-extrapodconfig), does not work, the value does not get passed onto the users container. Topic opened in Forum: https://discourse.jupyter.org/t/extrapodconfig-values-do-not-get-set/17868 (see also [Mattermost](https://mattermost.web.cern.ch/it-dep/pl/pp17jn5qdbggdjpihtkmawsxdc)

@garciagenrique see if you can follow my changes, the extra values I set are described in the [customization docs](https://z2jh.jupyter.org/en/stable/jupyterhub/customization.html). As I have no idea why the value does not get set, I'll have to wait for an answer in the Forum..

**Comment by goseind** [comment]
My workaround solution by setting the `fsGroup` to `0` in order to use root access didn't work as then the following error occurs: `Running as root is not recommended. Use --allow-root to bypass.` This has been a problem for other users too, see: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/562 or https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/2177
Also asking the SWAN team how they worked around this ref.: https://github.com/swan-cern/swan-charts/blob/master/swan/values.yaml#L22

**Comment by goseind** [comment]
To solve the issue with the `extraPodConfig` not being set, I created a bug report in the JupyterHub repo: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/3021

**Comment by garciagenrique** [comment]
@goseind could we just not set up a `podSecurityContext` for the moment, finish configuring JHub, and later implement this ?

**Comment by goseind** [comment]
No, as this is required for using the PVCs with non-root user's but you can try a different configuration with different storage options but I'm afraid it'll have the same issue. But feel free to experiment with different options.

**Comment by goseind** [comment]
Set a meeting with Diogo from SWAN for next week Monday and check their storage configuration with `eosxd`: https://gitlab.cern.ch/kubernetes/automation/charts/cern/-/tree/master/eosxd

**Comment by goseind** [comment]
For an update see #34, the service is now reachable from within CERN but needs further configuration, as listed in the issue description.
@garciagenrique can you add a PR with the cvmfs configuration?

**Comment by garciagenrique** [comment]
The base image of the ESCAPE-VRE is this one: https://gitlab.cern.ch/escape-wp2/docker-images/-/tree/master/datalake-singleuser 
There are some features that could be improved (maybe python version and latests rucio client versions ?), but all the configuration of how to add the rucio-jupyterlab plugin is linked here.

I suggest either start with this image, either based on it.

**Comment by goseind** [comment]
> > @goseind could we just not set up a `podSecurityContext` for the moment, finish configuring JHub, and later implement this ?
> 
> is there a solution to this? I've tried everything to get fsGroupChangePolicy: "OnRootMismatch" set. Nothing gets passed to the pod. Only setting the values in a yaml that is used to start the pod works. But nothing in the spawner works.

So far we haven't found a solution either, some values get set through the YAML values, but for the ones we need not, setting them with the extra config script doesn't work either. We need to further debug this.

**Comment by goseind** [comment]
@garciagenrique I now merged the config, from my side this looks fine. Do you want to take charge of redoing the images, also the EOS image? References can be found in the config of the images I was using/creating.

**Comment by goseind** [comment]
I think this issue could be closed and the *remaining* tasks split up into separate tasks as they are not directly linked to the initial goal of this issue. What do you think @garciagenrique ?

**Comment by garciagenrique** [comment]
I agree @goseind, although this issue become too big and touched plenty of subjects...

Could we start in this thread an interaction to summary the remaining tasks ?

**Comment by goseind** [comment]
In my opinion, this topic can now be closed as all the tasks have been completed.
